move_group:
  planner_id: "TRRT"
  planning_time: 10.0
  num_planning_attempts: 10 
  max_velocity_scaling_factor: 0.10
  max_acceleration_scaling_factor: 0.10
  end_effector_link: "tool0"
  pose_reference_frame: "base_link"

execute: false
planning : true


tasks:
  speed_test:
    stages:
      - name: move_home_cam
        type: move_to
        planner: interpolation
        target: home_camera_vertical
        vel_acc: [1.0, 1.0]

      - name: move_blue_pre_button
        type: move_to
        planner: interpolation
        target: blue_button
        offset: [0.0, 0.0, 0.1]

      - name: press_blue
        type: move_relative
        planner: cartesian
        target: blue_button
        direction: [0.0, 0.0, -1.0]
        minmax_dist: [0.105, 0.105]

      - name: retract_blue
        type: move_relative
        planner: cartesian
        target: blue_button
        direction: [0.0, 0.0, 1.0]
      
      - name: blue_to_pre_red
        type: move_to
        planner: interpolation
        target: red_button
        offset: [0.0, 0.0, 0.1]

      - name: press_red
        type: move_relative
        planner: cartesian
        target: red_button
        direction: [0.0, 0.0, -1.0]
        minmax_dist: [0.105, 0.105]

      - name: retract_red
        type: move_relative
        planner: cartesian
        target: red_button
        direction: [0.0, 0.0, 1.0]

      - name: move_home
        type: move_to
        planner: interpolation
        target: home_camera

  press_blue_button:
    stages:
      - name: move_home_cam
        type: move_to
        planner: interpolation
        target: home_camera_vertical
        vel_acc: [0.8, 0.8]

      - name: move_blue_pre_button
        type: move_to
        planner: interpolation
        target: blue_button
        offset: [0.0, 0.0, 0.1]

      - name: press_blue
        type: move_relative
        planner: cartesian
        target: blue_button
        direction: [0.0, 0.0, -1.0]
        minmax_dist: [0.105, 0.105]

      - name: retract_blue
        type: move_relative
        planner: cartesian
        target: blue_button
        direction: [0.0, 0.0, 1.0]

      - name: move_home
        type: move_to
        planner: interpolation
        target: home_camera


  press_red_button:
    stages:
      - name: move_home_cam
        type: move_to
        planner: interpolation
        target: home_camera_vertical
        vel_acc: [0.8, 0.8]

      - name: move_red_pre_button
        type: move_to
        planner: interpolation
        target: red_button
        offset: [0.0, 0.0, 0.1]

      - name: press_red
        type: move_relative
        planner: cartesian
        target: red_button
        direction: [0.0, 0.0, -1.0]
        minmax_dist: [0.105, 0.105]

      - name: retract_red
        type: move_relative
        planner: cartesian
        target: red_button
        direction: [0.0, 0.0, 1.0]

      - name: move_home
        type: move_to
        planner: interpolation
        target: home_camera

  pick_stylus:
    stages:
      - name: move_home_cam
        type: move_to
        planner: interpolation
        target: home_camera_vertical
        vel_acc: [0.5, 0.5]

      - name: approach_stylus
        type: move_to
        planner: interpolation
        target: stylus_pose
        offset: [0.0, 0.0, 0.1]
        vel_acc: [0.5, 0.5]

      - name: align_stylus
        type: move_relative
        planner: cartesian
        direction: [-1.0, 0.0, 0.0]
        minmax_dist: [0.01, 0.01]
        frame: ee_gripper
        vel_acc: [0.1, 0.1]

      - name: grab_stylus
        type: move_relative
        planner: cartesian
        direction: [0.0, 0.0, -1]
        minmax_dist: [0.103, 0.103]
        

  retract_stylus:
    stages:
      - name: stylus_retract
        type: move_relative
        planner: cartesian
        direction: [0.0, 0.0, 0.1]

      - name: move_home
        type: move_to
        planner: interpolation
        target: home_camera
        vel_acc: [0.8, 0.8]
      
      - name: rotate_touch
        type: move_to
        planner: interpolation
        target: home_camera_touch



  screen_approach:
    hand_frame: ee_touch
    stages:
      - name: screen_align
        type: move_to
        planner: interpolation
        target: screen_align_pose
        offset: [0.0, 0.0, 0.0]

      - name: screen_approach
        type: move_to
        planner: interpolation
        target: screen
        offset: [0.054, -0.033, 0.03]

  screen_draw:
    hand_frame: ee_touch
    stages:
      - name: align_background
        type: move_to
        planner: interpolation
        target: background
        offset: [0.0, 0.0, 0.03]

      - name: screen_draw_poses
        type: move_to_path
        planner: interpolation
        target: screen_draw_poses
        offset: [0.0, 0.0, -0.005]
        vel_acc: [0.05, 0.05]

      - name: retract_screen
        type: move_to
        planner: interpolation
        target: screen
        offset: [0.054, -0.033, 0.03]
        vel_acc: [0.1, 0.1]

  screen_text:
    hand_frame: ee_touch
    stages:
      - name: screen_text_poses
        type: move_to_path
        planner: interpolation
        target: screen_text_poses
        offset: [0.0, 0.0, 0.0]
        vel_acc: [0.05, 0.05]

      - name: retract_screen
        type: move_to
        planner: interpolation
        target: screen
        offset: [0.054, -0.033, 0.02]
        vel_acc: [0.1, 0.1]

  home_pose:
    stages:
      - name: align_screen
        type: move_relative
        planner: cartesian
        direction: [0.0, 0.0, 1.0]
        minmax_dist: [0.1, 0.1]

      - name: home_camera
        type: move_to
        planner: interpolation
        target: home_camera

  place_stylus:
    hand_frame: ee_gripper
    stages:
      - name: move_home_cam
        type: move_to
        planner: interpolation
        target: home_camera_vertical

      - name: approach_stylus
        type: move_to
        planner: interpolation
        target: stylus_pose
        offset: [0.0, 0.0, 0.1]

      - name: align_stylus
        type: move_relative
        planner: cartesian
        direction: [-1.0, 0.0, 0.0]
        minmax_dist: [0.01, 0.01]
        frame: ee_gripper

      - name: release_stylus
        type: move_relative
        planner: cartesian
        direction: [0.0, 0.0, -1]
        minmax_dist: [0.08, 0.08]

